language: python
sudo: false

python:
-  - 3.5.9
-  - 3.6.10
-  - 3.7.5
-  - 3.8.3
-  - 3.9.1

env:
  global:
    - PACKAGENAME="sigpyparser"

before_install:
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - pytest .
  - bash <(curl -s https://codecov.io/bash)
notifications:
email: false
